app:
  database-access-type: jpa
  scheduler:
    enable: true
    interval: 5000
    force-check-delay: 5000

spring:
  application:
    name: scrapper
  liquibase:
    enabled: false
  datasource:
    url: jdbc:postgresql://localhost:5432/scrapper
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

springdoc:
  swagger-ui:
    path: /swagger-ui

server:
  port: 8080

bot:
  base-url: http://localhost:8090

logging:
  config: classpath:log4j2-plain.xml
