app:
  scheduler:
    enable: true
    interval: 5000
    force-check-delay: 5000

spring:
  application:
    name: scrapper

springdoc:
  swagger-ui:
    path: /swagger-ui

server:
  port: 8080

bot:
  base-url: https://localhost:8090

logging:
  config: classpath:log4j2-plain.xml
