app:
  telegram-token: ${APP_TELEGRAM_TOKEN}

spring:
  application:
    name: bot
  jackson:
    time-zone: UTC
  liquibase:
    enabled: false

springdoc:
  swagger-ui:
    path: /swagger-ui

server:
  port: 8090

scrapper:
  base-url: http://localhost:8080

logging:
  config: classpath:log4j2-plain.xml
