/*
 * This file is generated by jOOQ.
 */
package edu.java.domain.jooq.scrapper_schema;


import edu.java.domain.jooq.DefaultCatalog;
import edu.java.domain.jooq.scrapper_schema.tables.Chat;
import edu.java.domain.jooq.scrapper_schema.tables.ChatLink;
import edu.java.domain.jooq.scrapper_schema.tables.Link;
import edu.java.domain.jooq.scrapper_schema.tables.Question;

import java.util.Arrays;
import java.util.List;

import javax.annotation.processing.Generated;

import org.jetbrains.annotations.NotNull;
import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ScrapperSchema extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>SCRAPPER_SCHEMA</code>
     */
    public static final ScrapperSchema SCRAPPER_SCHEMA = new ScrapperSchema();

    /**
     * The table <code>SCRAPPER_SCHEMA.CHAT</code>.
     */
    public final Chat CHAT = Chat.CHAT;

    /**
     * The table <code>SCRAPPER_SCHEMA.CHAT_LINK</code>.
     */
    public final ChatLink CHAT_LINK = ChatLink.CHAT_LINK;

    /**
     * The table <code>SCRAPPER_SCHEMA.LINK</code>.
     */
    public final Link LINK = Link.LINK;

    /**
     * The table <code>SCRAPPER_SCHEMA.QUESTION</code>.
     */
    public final Question QUESTION = Question.QUESTION;

    /**
     * No further instances allowed
     */
    private ScrapperSchema() {
        super("SCRAPPER_SCHEMA", null);
    }


    @Override
    @NotNull
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    @NotNull
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            Chat.CHAT,
            ChatLink.CHAT_LINK,
            Link.LINK,
            Question.QUESTION
        );
    }
}
