/*
 * This file is generated by jOOQ.
 */
package edu.java.domain.jooq.scrapper_schema;


import edu.java.domain.jooq.scrapper_schema.tables.Chat;
import edu.java.domain.jooq.scrapper_schema.tables.ChatLink;
import edu.java.domain.jooq.scrapper_schema.tables.Link;
import edu.java.domain.jooq.scrapper_schema.tables.Question;

import javax.annotation.processing.Generated;


/**
 * Convenience access to all tables in SCRAPPER_SCHEMA.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>SCRAPPER_SCHEMA.CHAT</code>.
     */
    public static final Chat CHAT = Chat.CHAT;

    /**
     * The table <code>SCRAPPER_SCHEMA.CHAT_LINK</code>.
     */
    public static final ChatLink CHAT_LINK = ChatLink.CHAT_LINK;

    /**
     * The table <code>SCRAPPER_SCHEMA.LINK</code>.
     */
    public static final Link LINK = Link.LINK;

    /**
     * The table <code>SCRAPPER_SCHEMA.QUESTION</code>.
     */
    public static final Question QUESTION = Question.QUESTION;
}
