/*
 * This file is generated by jOOQ.
 */
package edu.java.domain.jooq.scrapper_schema.tables.pojos;


import jakarta.validation.constraints.Size;

import java.beans.ConstructorProperties;
import java.io.Serializable;
import java.time.OffsetDateTime;

import javax.annotation.processing.Generated;

import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Link implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long id;
    private String url;
    private String type;
    private OffsetDateTime checkedAt;
    private OffsetDateTime lastUpdatedAt;
    private OffsetDateTime createdAt;

    public Link() {}

    public Link(Link value) {
        this.id = value.id;
        this.url = value.url;
        this.type = value.type;
        this.checkedAt = value.checkedAt;
        this.lastUpdatedAt = value.lastUpdatedAt;
        this.createdAt = value.createdAt;
    }

    @ConstructorProperties({ "id", "url", "type", "checkedAt", "lastUpdatedAt", "createdAt" })
    public Link(
        @Nullable Long id,
        @NotNull String url,
        @Nullable String type,
        @Nullable OffsetDateTime checkedAt,
        @Nullable OffsetDateTime lastUpdatedAt,
        @Nullable OffsetDateTime createdAt
    ) {
        this.id = id;
        this.url = url;
        this.type = type;
        this.checkedAt = checkedAt;
        this.lastUpdatedAt = lastUpdatedAt;
        this.createdAt = createdAt;
    }

    /**
     * Getter for <code>SCRAPPER_SCHEMA.LINK.ID</code>.
     */
    @Nullable
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>SCRAPPER_SCHEMA.LINK.ID</code>.
     */
    public void setId(@Nullable Long id) {
        this.id = id;
    }

    /**
     * Getter for <code>SCRAPPER_SCHEMA.LINK.URL</code>.
     */
    @jakarta.validation.constraints.NotNull
    @Size(max = 255)
    @NotNull
    public String getUrl() {
        return this.url;
    }

    /**
     * Setter for <code>SCRAPPER_SCHEMA.LINK.URL</code>.
     */
    public void setUrl(@NotNull String url) {
        this.url = url;
    }

    /**
     * Getter for <code>SCRAPPER_SCHEMA.LINK.TYPE</code>.
     */
    @Size(max = 48)
    @Nullable
    public String getType() {
        return this.type;
    }

    /**
     * Setter for <code>SCRAPPER_SCHEMA.LINK.TYPE</code>.
     */
    public void setType(@Nullable String type) {
        this.type = type;
    }

    /**
     * Getter for <code>SCRAPPER_SCHEMA.LINK.CHECKED_AT</code>.
     */
    @Nullable
    public OffsetDateTime getCheckedAt() {
        return this.checkedAt;
    }

    /**
     * Setter for <code>SCRAPPER_SCHEMA.LINK.CHECKED_AT</code>.
     */
    public void setCheckedAt(@Nullable OffsetDateTime checkedAt) {
        this.checkedAt = checkedAt;
    }

    /**
     * Getter for <code>SCRAPPER_SCHEMA.LINK.LAST_UPDATED_AT</code>.
     */
    @Nullable
    public OffsetDateTime getLastUpdatedAt() {
        return this.lastUpdatedAt;
    }

    /**
     * Setter for <code>SCRAPPER_SCHEMA.LINK.LAST_UPDATED_AT</code>.
     */
    public void setLastUpdatedAt(@Nullable OffsetDateTime lastUpdatedAt) {
        this.lastUpdatedAt = lastUpdatedAt;
    }

    /**
     * Getter for <code>SCRAPPER_SCHEMA.LINK.CREATED_AT</code>.
     */
    @Nullable
    public OffsetDateTime getCreatedAt() {
        return this.createdAt;
    }

    /**
     * Setter for <code>SCRAPPER_SCHEMA.LINK.CREATED_AT</code>.
     */
    public void setCreatedAt(@Nullable OffsetDateTime createdAt) {
        this.createdAt = createdAt;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Link other = (Link) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.url == null) {
            if (other.url != null)
                return false;
        }
        else if (!this.url.equals(other.url))
            return false;
        if (this.type == null) {
            if (other.type != null)
                return false;
        }
        else if (!this.type.equals(other.type))
            return false;
        if (this.checkedAt == null) {
            if (other.checkedAt != null)
                return false;
        }
        else if (!this.checkedAt.equals(other.checkedAt))
            return false;
        if (this.lastUpdatedAt == null) {
            if (other.lastUpdatedAt != null)
                return false;
        }
        else if (!this.lastUpdatedAt.equals(other.lastUpdatedAt))
            return false;
        if (this.createdAt == null) {
            if (other.createdAt != null)
                return false;
        }
        else if (!this.createdAt.equals(other.createdAt))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.url == null) ? 0 : this.url.hashCode());
        result = prime * result + ((this.type == null) ? 0 : this.type.hashCode());
        result = prime * result + ((this.checkedAt == null) ? 0 : this.checkedAt.hashCode());
        result = prime * result + ((this.lastUpdatedAt == null) ? 0 : this.lastUpdatedAt.hashCode());
        result = prime * result + ((this.createdAt == null) ? 0 : this.createdAt.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Link (");

        sb.append(id);
        sb.append(", ").append(url);
        sb.append(", ").append(type);
        sb.append(", ").append(checkedAt);
        sb.append(", ").append(lastUpdatedAt);
        sb.append(", ").append(createdAt);

        sb.append(")");
        return sb.toString();
    }
}
