/*
 * This file is generated by jOOQ.
 */
package edu.java.domain.jooq.scrapper_schema.tables.pojos;


import java.beans.ConstructorProperties;
import java.io.Serializable;

import javax.annotation.processing.Generated;

import org.jetbrains.annotations.Nullable;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Question implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long id;
    private Integer answerCount;
    private Long linkId;

    public Question() {}

    public Question(Question value) {
        this.id = value.id;
        this.answerCount = value.answerCount;
        this.linkId = value.linkId;
    }

    @ConstructorProperties({ "id", "answerCount", "linkId" })
    public Question(
        @Nullable Long id,
        @Nullable Integer answerCount,
        @Nullable Long linkId
    ) {
        this.id = id;
        this.answerCount = answerCount;
        this.linkId = linkId;
    }

    /**
     * Getter for <code>SCRAPPER_SCHEMA.QUESTION.ID</code>.
     */
    @Nullable
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>SCRAPPER_SCHEMA.QUESTION.ID</code>.
     */
    public void setId(@Nullable Long id) {
        this.id = id;
    }

    /**
     * Getter for <code>SCRAPPER_SCHEMA.QUESTION.ANSWER_COUNT</code>.
     */
    @Nullable
    public Integer getAnswerCount() {
        return this.answerCount;
    }

    /**
     * Setter for <code>SCRAPPER_SCHEMA.QUESTION.ANSWER_COUNT</code>.
     */
    public void setAnswerCount(@Nullable Integer answerCount) {
        this.answerCount = answerCount;
    }

    /**
     * Getter for <code>SCRAPPER_SCHEMA.QUESTION.LINK_ID</code>.
     */
    @Nullable
    public Long getLinkId() {
        return this.linkId;
    }

    /**
     * Setter for <code>SCRAPPER_SCHEMA.QUESTION.LINK_ID</code>.
     */
    public void setLinkId(@Nullable Long linkId) {
        this.linkId = linkId;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Question other = (Question) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.answerCount == null) {
            if (other.answerCount != null)
                return false;
        }
        else if (!this.answerCount.equals(other.answerCount))
            return false;
        if (this.linkId == null) {
            if (other.linkId != null)
                return false;
        }
        else if (!this.linkId.equals(other.linkId))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.answerCount == null) ? 0 : this.answerCount.hashCode());
        result = prime * result + ((this.linkId == null) ? 0 : this.linkId.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Question (");

        sb.append(id);
        sb.append(", ").append(answerCount);
        sb.append(", ").append(linkId);

        sb.append(")");
        return sb.toString();
    }
}
